### ISSUE TITLE
运行报RuntimeUnavailableError错误

### ISSUE THREAD

**Issue by jsk188** [rhming/UnicomDailyTask#15]
日志如下
2021/10/29 15:45:03 GMT+08:00 07f8bfa4-3ea9-4291-84f5-6aec7af3ef46 Function invocation catch a 'RuntimeUnavailableError' exception(Could not find an available JavaScript runtime.)
Traceback (most recent call last):
  File "./index.py", line 118, in main_handler
    Template(SigninApp)
  File "./index.py", line 38, in Template
    ts.append(Thread(target=cls(mobile, password).run))
  File "./activity/unicom/dailySign.py", line 16, in __init__
    super(SigninApp, self).__init__(mobile, password)
  File "./utils/unicomLogin.py", line 32, in __init__
    self.login()
  File "./utils/unicomLogin.py", line 90, in login
    "mobile": self.JSEncrypt(self.mobile),
  File "./utils/unicomLogin.py", line 70, in JSEncrypt
    ctx = execjs.compile(js)
  File "./execjs/__init__.py", line 61, in compile
    return get().compile(source, cwd)
  File "./execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "./execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.

**Comment by jsk188** [comment]
之前上传错代码包了，打扰大佬了
