### ISSUE TITLE
测试报错

### ISSUE THREAD

**Issue by ez452** [rhming/UnicomDailyTask#4]
Exception in thread Thread-8:

Traceback (most recent call last):

    self.run()

  File "/var/lang/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner

  File "/var/lang/python3/lib/python3.6/threading.py", line 864, in run

  File "/var/user/activity/wolearn/stdt4.py", line 232, in run

    if self.answer(item, answerId) == 1:

    self._target(*self._args, **self._kwargs)

    return int(result['data']['status'])

TypeError: string indices must be integers

  File "/var/user/activity/wolearn/stdt4.py", line 153, in answer

Response RequestId:38ac6135-e9ab-46e3-9f19-02a9c5737454 RetMsg:null

END RequestId:38ac6135-e9ab-46e3-9f19-02a9c5737454

Report RequestId:38ac6135-e9ab-46e3-9f19-02a9c5737454 Duration:50003ms Memory:128MB MemUsage:83.253906MB
麻烦大佬看一下还有哪部分是需要改的，还有个小建议，能不能加个推送啊，谢谢

**Comment by rhming** [comment]
已修复，重新下载上传到云函数. 近一个月的活动抽奖记录都会存到搭建的数据存储服务上 可以登录管理后台查看

**Comment by jkluio78** [comment]
> 已修复，重新下载上传到云函数. 近一个月的活动抽奖记录都会存到搭建的数据存储服务上 可以登录管理后台查看

请问大佬管理后台的网址是什么？如何查看运行数据？

**Comment by rhming** [comment]
[pythonanywhere仓库](https://github.com/rhming/pythonanywhere)搭建的数据存储服务 访问`用户名.pythonanywhere.com`，界面上有`管理后台`选项, 已添加消息推送 需要重新上传到云函数
