### ISSUE TITLE
跑微博任务报错

### ISSUE THREAD

**Issue by YorkMoon** [rhming/UnicomDailyTask#41]
手机Termux上跑的，按 #13 填写相应值，跑微博任务报错。请问怎么解决？

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/storage/emulated/0/Termux/UnicomDailyTask/activity/unicom/zhuanjifenWeiBo.py", line 219, in run
    wbsign = json.loads(fp.read())
  File "/storage/emulated/0/Termux/UnicomDailyTask/utils/jsonencode.py", line 13, in loads
    return jsonpickle.loads(value)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 49, in decode
    data = backend.decode(string)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/jsonpickle/backend.py", line 207, in decode
    return self.backend_decode(name, string)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/jsonpickle/backend.py", line 220, in backend_decode
    return self._decoders[name](string, *optargs, **decoder_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

**Comment by rhming** [comment]
`from utils import jsonencode as json`这行改成`import json`
或者
`utils/jsonencode.py`文件中 把`jsonpickle.set_decoder_options('json', encoding='utf8')`改成`jsonpickle.set_decoder_options('json')`

**Comment by YorkMoon** [comment]
可以了，非常感谢！
还想问下多台设备抓取的 deviceId 和 androidId 该怎样填写？
