### ISSUE TITLE
未获取到日志

### ISSUE THREAD

**Issue by TW00909** [rhming/UnicomDailyTask#53]
华为云函数工作流运行，有2个任务好像没有执行，观察了两天的日志都是空的。
-------------13105740011SigninAppRecord[2021-12-20]-------------
未获取到日志
-----------13105740011WatchAddFlowRecord[2021-12-20]------------
未获取到日志

**Comment by TW00909** [comment]
Traceback (most recent call last):
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/function/code/activity/unicom/dailySign.py", line 108, in run
    if not self.getContinuous():
  File "/opt/function/code/activity/unicom/dailySign.py", line 60, in getContinuous
    data = result['data']  # ['daySignList']
KeyError: 'data'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/function/code/activity/unicom/watchAddFee.py", line 48, in run
    task = self.listTaskInfo()
  File "/opt/function/code/activity/unicom/watchAddFee.py", line 33, in listTaskInfo
    return result['data']
KeyError: 'data'

**Comment by rhming** [comment]
这是登录了多台设备 被挤下线了
进入搭建的数据存储后台删掉`手机号WoGame`的数据项

**Comment by TW00909** [comment]
非常感谢！
再请问deviceIds 是直接填写手机15位数字imei 还是填写APP抓包取得的deviceCode？

**Comment by rhming** [comment]
抓包cookie中字段`d_deviceCode`的值就是获取到的设备imei,填写`d_deviceCode`就行

**Comment by TW00909** [comment]
已完美解决！
