### ISSUE TITLE
一个小问题，不影响正常功能，报告一下

### ISSUE THREAD

**Issue by snioer** [rhming/UnicomDailyTask#61]
`Exception in thread Thread-12:
Traceback (most recent call last):
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/function/code/activity/unicom/unicomSignerTask.py", line 69, in run
    taskList = self.findTask()
  File "/opt/function/code/activity/unicom/unicomSignerTask.py", line 41, in findTask
    taskList = data['data']['showTask']
TypeError: 'NoneType' object is not subscriptable

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/function/code/activity/unicom/unicomTurnTable.py", line 118, in run
    playCounts, useCount = self.list()
  File "/opt/function/code/activity/unicom/unicomTurnTable.py", line 38, in list
    return data['data']['playCounts'], data['data']['useCount']
TypeError: 'NoneType' object is not subscriptable
`
查了一下，是把return None的方法赋给了变量
希望可以定位一下

**Comment by rhming** [comment]
刚看了一下,这个任务活动已经结束了,所以没有获取到数据
![image](https://user-images.githubusercontent.com/49028484/150123118-4b6d9656-94e2-43b3-ae9e-e0764f1c3176.png)
+ index.py文件里 `Template(TurnTable)`这一行删掉或注释掉就行

**Comment by snioer** [comment]
好的，谢谢
