### ISSUE TITLE
查看日志时，发现以下报错。

### ISSUE THREAD

**Issue by XavierLee-0** [rhming/UnicomDailyTask#69]
```
###########################readCookie########################### 132
##############################run############################### 132
############################getTask############################# 132
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/function/code/activity/unicom/superSimpleTask.py", line 90, in run
    for item in self.getTask('superEasy'):
  File "/opt/function/code/activity/unicom/superSimpleTask.py", line 34, in getTask
    return data['data']
KeyError: 'data'

2022/01/29 13:15:05 GMT+08:00 Finish invoke request 'd9b83190-384b-4dca-ab14-9bb438d188f8', duration: 3206.323ms, billing duration: 3300ms, memory used: 109.637MB, rss memory used: 40.309MB.
```

**Comment by XavierLee-0** [comment]
还看到日志里面有提示{"dsc":"系统检测到您的账户登录过于频繁，为保证您的账户安全，请您稍后再试","code":"3"}

**Comment by onesixsix** [comment]
号黑了吗，手动登营业厅看看

**Comment by XavierLee-0** [comment]
> 号黑了吗，手动登营业厅看看

登陆了，但是没看出什么端倪。

**Comment by XavierLee-0** [comment]
请问登陆了联通app的话，退出登录是选择“解绑并退出登录”还是“仅退出登录”呢？

**Comment by XavierLee-0** [comment]
> 登录了多台设备,配置文件`deviceId`和`appId`要与手机登录的一致才不会挤下线,因挤下线导致登录过多 deviceId填写抓包Cookie中的`d_deviceCode`字段

请问登陆了联通app的话，退出登录是选择“解绑并退出登录”还是“仅退出登录”呢？

**Comment by rhming** [comment]
仅退出登录,如果填写的配置与手机上登录时一样,都可以不用退出
联通App至少要授予`获取手机信息` `读写手机存储`两个权限
