### ISSUE TITLE
华为函数执行报错

### ISSUE THREAD

**Issue by YYxiaoma** [rhming/UnicomDailyTask#72]
老哥，请问下这个报错是什么原因导致的？
![1644990749(1)](https://user-images.githubusercontent.com/41948565/154204656-89301699-1ec8-4956-9d37-2d4cbd676ad1.png)

有了APPID之后就不报上面的错误了，而是下面的错误，看了下issue，并没有看到类似的错误

############################getTask############################# 17***
Exception in thread Thread-3:
Traceback (most recent call last):
File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/opt/function/code/activity/unicom/superSimpleTask.py", line 131, in run
if int(item['achieve']) == int(item['allocation']) and item['btn'] != '已完成': # int(item['showStyle']) != 3:
KeyError: 'achieve'

**Comment by YYxiaoma** [comment]
请问下苹果手机怎么抓APPID？

刚刚在网上找到了方法
苹果手机抓这个：https://m.client.10010.com/mobileService/customer/getclientconfig.htm            请求头里面有appId

**Comment by c526796017** [comment]
> 请问下苹果手机怎么抓APPID？或者使用其他安卓手机的APPID是否允许？

苹果手机抓这个：https://m.client.10010.com/mobileService/customer/getclientconfig.htm，请求头里面有appId

**Comment by c526796017** [comment]
有了APPID之后就不报第一个错误了，而是下面的错误，看了下issue，并没有看到类似的错误

############################getTask############################# 17***
Exception in thread Thread-3:
Traceback (most recent call last):
File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/opt/function/code/activity/unicom/superSimpleTask.py", line 131, in run
if int(item['achieve']) == int(item['allocation']) and item['btn'] != '已完成':  # int(item['showStyle']) != 3:
KeyError: 'achieve'

**Comment by rhming** [comment]
这应该是没有登录状态,搭建的数据存储服务登录后台管理删除`手机号WoGame`的字段,再重新执行一遍看看

**Comment by c526796017** [comment]
> 这应该是没有登录状态,搭建的数据存储服务登录后台管理删除`手机号WoGame`的字段,再重新执行一遍看看

确实就是这个问题，已解决，TKS

**Comment by YYxiaoma** [comment]
> 这应该是没有登录状态,搭建的数据存储服务登录后台管理删除`手机号WoGame`的字段,再重新执行一遍看看

确实就是这个导致的，已解决，TKS
